accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup', views.SignUpView.as_view(), name='signup'),
]

gourmet_guide/urls.py
from django.urls import path
from . import views

app_name = 'gourmet_guide'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name="detail"),
    path('create/', views.CreateView.as_view(), name="create"),
    path('<int:pk>/update/', views.UpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name="delete"),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('gourmet_guide/', include('gourmet_guide.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='gourmet_guide/')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

gourmet_guide/models.py
from django.db import models
from django.urls import reverse
from django.dispatch import receiver


# カテゴリモデル: 飲食店のカテゴリ（例: フレンチ、イタリアン、寿司など）を表現
class Category(models.Model):
    # カテゴリの名前を格納する文字列フィールド
    name = models.CharField(max_length=255)
    
    # カテゴリを作成したユーザーとのリレーションシップを表現
    author = models.ForeignKey(
        'auth.User',  # Djangoのデフォルトのユーザーモデルを指定
        on_delete=models.CASCADE,  # ユーザーが削除された場合、関連するカテゴリも削除
    )
    
    # カテゴリの作成日時を格納する日時フィールド（自動的に追加される）
    created_at = models.DateTimeField(auto_now_add=True)
    
    # カテゴリの更新日時を格納する日時フィールド（自動的に更新される）
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # カテゴリの名前を文字列として返す（管理画面などで表示される）
        return self.name

# 店舗モデル: 飲食店の情報を表現
class Shop(models.Model):
    # 飲食店の名前を格納する文字列フィールド
    name = models.CharField(max_length=255)
    
    # 飲食店の住所を格納する文字列フィールド
    address = models.CharField(max_length=255)

    # 画像pathを保存するためのフィールド
    image = models.ImageField(upload_to='images', null=True)
    
    # 飲食店を作成したユーザーとのリレーションシップを表現
    author = models.ForeignKey(
        'auth.User',  # Djangoのデフォルトのユーザーモデルを指定
        on_delete=models.CASCADE,  # ユーザーが削除された場合、関連する店舗も削除
    )
    
    # 飲食店のカテゴリとのリレーションシップを表現
    category = models.ForeignKey(
        Category,  # カテゴリモデルとのリレーションシップ
        on_delete=models.PROTECT,  # 関連するカテゴリが削除ても削除されない
    )
    
    # 飲食店の作成日時を格納する日時フィールド（自動的に追加される）
    created_at = models.DateTimeField(auto_now_add=True)
    
    # 飲食店の更新日時を格納する日時フィールド（自動的に更新される）
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # 飲食店の名前を文字列として返す（管理画面などで表示される）
        return self.name
    
    def get_absolute_url(self):
        return reverse('gourmet_guide:detail', kwargs={'pk': self.pk})

# 画像ファイルの削除
@receiver(models.signals.post_delete, sender=Shop)
def auto_delete_image(sender, instance, **kwargs):
    file = instance.image
    file.storage.delete(name=file.name)
    

gourmet_guide/forms.py
from django import forms
from django.core.exceptions import ValidationError
from hashlib import sha256
from .models import Shop

import time

class ShopCreateForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ["name", "address", "category", "image"]

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            # 1. 画像ファイルの拡張子を確認
            allowed_extensions = ['jpg','jpeg','png']
            file_extension = image.name.lower().split('.')[-1]
            print("file_extension",file_extension)
            if not any(file_extension.endswith(ext) for ext in allowed_extensions):
                raise ValidationError("JPEGまたはPNGフォーマットの画像ファイルをアップロードしてください。")

            # 2. ファイル名をハッシュ化
            time_int = int(time.time())
            hashed_filename = sha256(image.name.encode()).hexdigest()[:10] # ファイル名をハッシュ化して10文字までにする
            image.name = f"{hashed_filename}{str(time_int)}.{file_extension}"

        return image

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
  form_class = UserCreationForm
  success_url = reverse_lazy('login')
  template_name = 'accounts/signup.html'

gourmet_guide/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Category, Shop
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from .forms import ShopCreateForm

import requests
import urllib

class IndexView(generic.ListView):
    model = Shop

class DetailView(generic.DetailView):
    # ↓ 使用するテンプレートファイルを指定
    template_name = 'gourmet_guide/wonderful_shop_detail.html'
    model = Shop

    # テンプレートにデータを渡すため
    def get_context_data(self, **kwargs):
        # 親クラスのメソッドを呼び出し
        context = super().get_context_data(**kwargs)
        
        # Shopモデルのインスタンスから住所フィールドを取得
        shop_instance = self.get_object()
        address = shop_instance.address

        # (国土地理院のAPI)
        ## エンドポイント
        makeUrl = "https://msearch.gsi.go.jp/address-search/AddressSearch?q="
        # エンコード(https://tech-unlimited.com/urlencode.html)
        s_quote = urllib.parse.quote(address)
        # print("S_quote", s_quote)

        response = requests.get(makeUrl + s_quote)
        print("response", response)

        coordinates = response.json()[0]["geometry"]["coordinates"]
        print("coordinates", coordinates)

        reversed_coordinates = reversed(coordinates)

        context['coordinates'] = ",".join(map(str, reversed_coordinates))
        print("context['coordinates']", context['coordinates'])
        print(context)

        return context

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Shop
    form_class = ShopCreateForm

    # フォームデータを取得し、データベースに保存するなどの操作を行う
    def form_valid(self, form):
        # authorにログインしているユーザー名を代入
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)


class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Shop
    fields = ['name', 'address', 'category', 'image'] 

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to edit.')
        return super(UpdateView, self).dispatch(request, *args, **kwargs)

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Shop
    success_url = reverse_lazy('gourmet_guide:index')

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>Sign up</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Sign up</button>
    </form>
</section>
{% endblock %}

gourmet_guide/templates/gourmet_guide/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shop list</title>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark fixed-top">
    <div class="container">
      <a class='navbar-brand' href='{% url "gourmet_guide:index" %}'>おすすめご飯やさん</a>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

gourmet_guide/templates/gourmet_guide/shop_confirm_delete.html
<!-- ファイルpathを省略するとプロジェクト全体のテンプレートを使用 -->
{% extends 'layout.html' %} 

<!-- コンテンツ開始 -->
{% block content %}

<h1>お店情報の削除</h1>
<p>「{{ object.name }}」を削除しますか？</p>
<form action="" method="POST">
  {% csrf_token %}
  <button type="submit" class="submit delete">削除</button>
</form>
<div>
  <a href="Javascript:history.back()">&lt; 戻る</a>
</div>
<!-- コンテンツ終了 -->
{% endblock %}

gourmet_guide/templates/gourmet_guide/shop_form.html
<!-- ファイルpathを省略するとプロジェクト全体のテンプレートを使用 -->
{% extends 'layout.html' %} 

<!-- コンテンツ開始 -->
{% block content %}

<h1>お店情報の{{ object|yesno:'更新,作成' }}</h1>

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="submit">
    {{ object|yesno:'更新,作成' }}
  </button>
</form>

<div>
  <a href="Javascript:history.back()">&lt; 戻る</a>
</div>
<!-- コンテンツ終了 -->
{% endblock %}

gourmet_guide/templates/gourmet_guide/shop_list.html
<!-- ファイルpathを省略するとプロジェクト全体のテンプレートを使用 -->
{% extends 'layout.html' %} 

<!-- コンテンツ開始 -->
{% block content %}
  <h1>お店一覧</h1>
  {% if user.is_authenticated %}
  <div>
    <a href="{% url 'gourmet_guide:create' %}">新規登録</a>
  </div>
  {% endif %}
  <table class="table table-striped table-hover">
    <tr>
      <th>店名</th>
      <th>カテゴリー</th>
      <th>住所</th>
      <th>イメージ</th>
    </tr>
    {% for shop in object_list %}
    <tr>
      <td><a href="{% url 'gourmet_guide:detail' shop.pk %}">{{ shop.name }}</a></td>
      <td>{{ shop.category.name }}</td>
      <td>{{ shop.address }}</td>
      <td><img src="/media/{{ shop.image }}" alt="" width="100px"></td>
    </tr>
    {% endfor %}
  </table>
<!-- コンテンツ終了 -->
{% endblock %}

gourmet_guide/templates/gourmet_guide/wonderful_shop_detail.html
<!-- ファイルpathを省略するとプロジェクト全体のテンプレートを使用 -->
{% extends 'layout.html' %} 

<!-- コンテンツ開始 -->
{% block content %}
<h1>{{ shop.name }}</h1>

<div>
  <p>{{ shop.category.name }}</p>
  <p>{{ shop.address }}</p>
</div>
<!-- 確認用 → {{ coordinates }} -->
<iframe src='https://maps.google.co.jp/maps?output=embed&q={{coordinates}}&z=16' allowfullscreen="" width="1000px" height="300px"></iframe>
<div>
  <a href="{% url 'gourmet_guide:index' %}">一覧ページへ</a>
  {% if request.user.id == object.author_id %}
    <a href="{% url 'gourmet_guide:update' shop.pk %}">編集</a>
    <a href="{% url 'gourmet_guide:delete' shop.pk %}">削除</a>
  {% endif %}
</div>
<!-- コンテンツ終了 -->
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shop list</title>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark fixed-top">
    <div class="container">
      <a class='navbar-brand' href='{% url "gourmet_guide:index" %}'>おすすめご飯やさん</a>
      <ul class='navbar-nav'>
        {% if user.is_authenticated %}
            <li class='nav-time'>
                <span class='navbar-text'>{{ user }} - </span>
            </li>
            <li class='nav-item'>
                <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
            </li>
        {% else %}
        <li>
          <a href='{% url "login" %}' class='login nav-link'>Login</a>
        </li>
        <li>
          <a href='{% url "accounts:signup" %}' class='signup nav-link'> Sign up </a>
        </li>
        {% endif %}
    </ul>
    </div>
   
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>